name: Deploy to K8s

on:
  workflow_run:
    workflows: ["docker build and push "]
    types: [completed]

jobs:
  my-88888888888-job:
    runs-on: ubuntu-latest

    steps:
      - run: echo $MY_ENV
        env:
          MY_ENV: ${{ toJSON(github.event) }}

      - run: echo $MY_ENV
        env:
          MY_ENV: ${{ toJSON(github.event.workflow_run) }}
