
name: my-first-actions

on: [ push ]

jobs:
  my-first-job:
    
    runs-on: ubuntu-latest
    # runs-on: windows-latest
    # runs-on: macos-latest

    steps:
      # use (community action) to downloads the repo files
      - uses: actions/checkout@v2

      - run: ls -al /home/runner/work/
      - run: ls -al /home/runner/work/test_actions/
      - run: ls -al /home/runner/work/test_actions/test_actions/
      - run: |
          uname
          whoami
          echo "Done"


  my-second-job:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: pwd # /home/runner/work/test_actions/test_actions
      - run: cd /tmp/
      - run: pwd # /home/runner/work/test_actions/test_actions


  my-third-job:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: make all
      

  my-env-job:
    runs-on: ubuntu-latest
    steps:
      - run: echo $MY_NAME
        env:
          MY_NAME: Asim

      - run: echo $NAME_1 $name_2 $Name_3
        env:
          NAME_1: asim
          name_2: bader
          Name_3: Ahmed

