
name: my-context-actions
on: [ push ]
jobs:
  my-env-job:
    runs-on: ubuntu-latest
    steps:
      - run: echo github.actor = ${{ github.actor }}
        # asim3
      - run: echo github.event_name = ${{ github.event_name }}
        # push
      - run: echo head_commit.message = ${{ github.event.head_commit.message }}
      - run: echo repository.default_branch = ${{ github.event.repository.default_branch }}
      - run: echo repository.full_name = ${{ github.event.repository.full_name }}
      - run: echo name = ${{ github.event.repository.name }}
      - run: echo xxx = ${{ github.event.xxx }}
      - run: echo xxx = ${{ github.event.xxx }}
      - run: echo xxx = ${{ github.event.xxx }}
      - run: echo xxx = ${{ github.event.xxx }}
        # 
        


      - run: MY_NEW_ENV="Asim"

      - run: echo "env $AS_JSON"
        env:
          AS_JSON: ${{ toJSON(env) }}
        # env {}

      - run: echo "github.event $AS_JSON"
        env:
          AS_JSON: ${{ toJSON(github.event) }}
        # github.event {
        #   "repository.full_name": {
        #     "archive_url": "https://api.github.com/repos/asim3/test_actions/{archive_format}{/ref}",
        #     "archived": false,
        #     "assignees_url": "https://api.github.com/repos/asim3/test_actions/assignees{/user}",
        #     "blobs_url": "https://api.github.com/repos/asim3/test_actions/git/blobs{/sha}",
        #     "branches_url": "https://api.github.com/repos/asim3/test_actions/branches{/branch}",
        #     "clone_url": "https://github.com/asim3/test_actions.git",
        #     "collaborators_url": "https://api.github.com/repos/asim3/test_actions/collaborators{/collaborator}",
        #     "comments_url": "https://api.github.com/repos/asim3/test_actions/comments{/number}",
        #     "commits_url": "https://api.github.com/repos/asim3/test_actions/commits{/sha}",
        #     "compare_url": "https://api.github.com/repos/asim3/test_actions/compare/{base}...{head}",
        #     "contents_url": "https://api.github.com/repos/asim3/test_actions/contents/{+path}",
        #     "contributors_url": "https://api.github.com/repos/asim3/test_actions/contributors",
        #     "created_at": 1622285864,
        #     "default_branch": "master",
        #     "deployments_url": "https://api.github.com/repos/asim3/test_actions/deployments",
        #     "description": null,
        #     "disabled": false,
        #     "downloads_url": "https://api.github.com/repos/asim3/test_actions/downloads",
        #     "events_url": "https://api.github.com/repos/asim3/test_actions/events",
        #     "fork": false,
        #     "forks": 0,
        #     "forks_count": 0,
        #     "forks_url": "https://api.github.com/repos/asim3/test_actions/forks",
        #     "full_name": "asim3/test_actions",
        #     "git_commits_url": "https://api.github.com/repos/asim3/test_actions/git/commits{/sha}",
        #     "git_refs_url": "https://api.github.com/repos/asim3/test_actions/git/refs{/sha}",
        #     "git_tags_url": "https://api.github.com/repos/asim3/test_actions/git/tags{/sha}",
        #     "git_url": "git://github.com/asim3/test_actions.git",
        #     "has_downloads": true,
        #     "has_issues": true,
        #     "has_pages": false,
        #     "has_projects": true,
        #     "has_wiki": true,
        #     "homepage": null,
        #     "hooks_url": "https://api.github.com/repos/asim3/test_actions/hooks",
        #     "html_url": "https://github.com/asim3/test_actions",
        #     "id": 371949281,
        #     "issue_comment_url": "https://api.github.com/repos/asim3/test_actions/issues/comments{/number}",
        #     "issue_events_url": "https://api.github.com/repos/asim3/test_actions/issues/events{/number}",
        #     "issues_url": "https://api.github.com/repos/asim3/test_actions/issues{/number}",
        #     "keys_url": "https://api.github.com/repos/asim3/test_actions/keys{/key_id}",
        #     "labels_url": "https://api.github.com/repos/asim3/test_actions/labels{/name}",
        #     "language": "Makefile",
        #     "languages_url": "https://api.github.com/repos/asim3/test_actions/languages",
        #     "license": null,
        #     "master_branch": "master",
        #     "merges_url": "https://api.github.com/repos/asim3/test_actions/merges",
        #     "milestones_url": "https://api.github.com/repos/asim3/test_actions/milestones{/number}",
        #     "mirror_url": null,
        #     "name": "test_actions",
        #     "node_id": "MDEwOlJlcG9zaXRvcnkzNzE5NDkyODE=",
        #     "notifications_url": "https://api.github.com/repos/asim3/test_actions/notifications{?since,all,participating}",
        #     "open_issues": 0,
        #     "open_issues_count": 0,
        #     "owner": {
        #       "avatar_url": "https://avatars.githubusercontent.com/u/48256968?v=4",
        #       "email": "48256968+asim3@users.noreply.github.com",
        #       "events_url": "https://api.github.com/users/asim3/events{/privacy}",
        #       "followers_url": "https://api.github.com/users/asim3/followers",
        #       "following_url": "https://api.github.com/users/asim3/following{/other_user}",
        #       "gists_url": "https://api.github.com/users/asim3/gists{/gist_id}",
        #       "gravatar_id": "",
        #       "html_url": "https://github.com/asim3",
        #       "id": 48256968,
        #       "login": "asim3",
        #       "name": "asim3",
        #       "node_id": "MDQ6VXNlcjQ4MjU2OTY4",
        #       "organizations_url": "https://api.github.com/users/asim3/orgs",
        #       "received_events_url": "https://api.github.com/users/asim3/received_events",
        #       "repos_url": "https://api.github.com/users/asim3/repos",
        #       "site_admin": false,
        #       "starred_url": "https://api.github.com/users/asim3/starred{/owner}{/repo}",
        #       "subscriptions_url": "https://api.github.com/users/asim3/subscriptions",
        #       "type": "User",
        #       "url": "https://api.github.com/users/asim3"
        #     },
        #     "private": false,
        #     "pulls_url": "https://api.github.com/repos/asim3/test_actions/pulls{/number}",
        #     "pushed_at": 1622381408,
        #     "releases_url": "https://api.github.com/repos/asim3/test_actions/releases{/id}",
        #     "size": 34,
        #     "ssh_url": "git@github.com:asim3/test_actions.git",
        #     "stargazers": 0,
        #     "stargazers_count": 0,
        #     "stargazers_url": "https://api.github.com/repos/asim3/test_actions/stargazers",
        #     "statuses_url": "https://api.github.com/repos/asim3/test_actions/statuses/{sha}",
        #     "subscribers_url": "https://api.github.com/repos/asim3/test_actions/subscribers",
        #     "subscription_url": "https://api.github.com/repos/asim3/test_actions/subscription",
        #     "svn_url": "https://github.com/asim3/test_actions",
        #     "tags_url": "https://api.github.com/repos/asim3/test_actions/tags",
        #     "teams_url": "https://api.github.com/repos/asim3/test_actions/teams",
        #     "trees_url": "https://api.github.com/repos/asim3/test_actions/git/trees{/sha}",
        #     "updated_at": "2021-05-30T13:28:37Z",
        #     "url": "https://github.com/asim3/test_actions",
        #     "watchers": 0,
        #     "watchers_count": 0
        #   },
        #   "sender": {
        #     "avatar_url": "https://avatars.githubusercontent.com/u/48256968?v=4",
        #     "events_url": "https://api.github.com/users/asim3/events{/privacy}",
        #     "followers_url": "https://api.github.com/users/asim3/followers",
        #     "following_url": "https://api.github.com/users/asim3/following{/other_user}",
        #     "gists_url": "https://api.github.com/users/asim3/gists{/gist_id}",
        #     "gravatar_id": "",
        #     "html_url": "https://github.com/asim3",
        #     "id": 48256968,
        #     "login": "asim3",
        #     "node_id": "MDQ6VXNlcjQ4MjU2OTY4",
        #     "organizations_url": "https://api.github.com/users/asim3/orgs",
        #     "received_events_url": "https://api.github.com/users/asim3/received_events",
        #     "repos_url": "https://api.github.com/users/asim3/repos",
        #     "site_admin": false,
        #     "starred_url": "https://api.github.com/users/asim3/starred{/owner}{/repo}",
        #     "subscriptions_url": "https://api.github.com/users/asim3/subscriptions",
        #     "type": "User",
        #     "url": "https://api.github.com/users/asim3"
        #   }
        # }


      - run: echo "runner $AS_JSON"
        env:
          AS_JSON: ${{ toJSON(runner) }}
        # runner {
        #   "os": "Linux",
        #   "tool_cache": "/opt/hostedtoolcache",
        #   "temp": "/home/runner/work/_temp",
        #   "workspace": "/home/runner/work/test_actions"
        # }


      - run: echo "needs $AS_JSON"
        env:
          AS_JSON: ${{ toJSON(needs) }}
        # needs {}

      - run: echo env.MY_NEW_ENV ${{ env.MY_NEW_ENV }}
        # 
