
name: my-triggers-actions

on: [ push ]

jobs:
  my-first-job:
    runs-on: ubuntu-latest
    steps:
      - run: ls -al /home/runner/work/_PipelineMapping
      - run: cat /home/runner/perflog/Runner.perf
      - run: cat /home/runner/perflog/Worker.perf
      - run: cat /home/runner/_PipelineMapping/asim3/test_actions/PipelineFolder.json

