
name: my-case-actions

on: [ push ]

jobs:
  case_1:
    runs-on: ubuntu-latest
    if: ${{ contains('Hello world', 'or') }}
    steps:
      - run: echo OK 1

      - run: echo OK 2
        if: ${{ contains('Hello world', 'or') }}

      - run: echo OK 3
        if: ${{ contains('Hello world', 'ZZ') }}
