
name: my-strategy-actions
on: [ push ]
jobs:
  my-env-job:
    runs-on: ubuntu-latest
    strategy:
      # will run 6 jobs
      matrix:
        my-name: ["Bader", "Ahmed"]
        my_order: [1, 2, 3]
    steps:
      - run: echo "$STRATEGY_CONTEXT"
        env:
          STRATEGY_CONTEXT: ${{ toJSON(strategy) }}
