
name: my-matrix-actions
on: [ push ]
jobs:
  my-env-job:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      # false = ignore errors
      matrix:
        my-name: ["Bader", "Ahmed"]
        my_order: [1, 2, 3]
    steps:
      - run: echo ${{ matrix.my-name }}
      
      - run: echo ${{ matrix.my_order }}

      - run: echo "$MATRIX_CONTEXT"
        env:
          MATRIX_CONTEXT: ${{ matrix }}
