
name: my-matrix-actions
on: [ push ]
jobs:
  my-env-job:
    runs-on: ubuntu-latest
    outputs:
      matrix: "my name is Ahmed"
    steps:
      
      - run: echo "$MATRIX_CONTEXT"
        env:
          MATRIX_CONTEXT: ${{ toJSON(matrix) }}

