
name: my-triggers-actions

on: [ push ]

jobs:
  my-first-job:
    runs-on: ubuntu-latest
    steps:
      - run: ls -al /home/runner/work/_PipelineMapping
      - run: sudo apt install -y tree
      - run: tree /home/runner/

