
name: my-triggers-actions

on:
  push:
    branches:
      - master
    tags:
      - v\d+\.\d+\.\d+

jobs:
  my-first-job:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${GITHUB_REF}
        # refs/heads/master
      - run: echo ${GITHUB_REF##*/}
        # master
      - run: |
          if [ "${GITHUB_REF##*/}" = "master" ]; then
            echo OK
          else
            echo Tag
          fi
