
name: my-ci-actions

on: [ push ]

jobs:
  my-first-job:
    runs-on: ${{ matrix.os }}
    strategy:
      martix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      # use (community action) to downloads the repo files
      - uses: actions/checkout@v2

      - run: ls -al /home/runner/work/

