
name: my-contexts-actions
on: [ push ]
jobs:
  my-env-job:
    runs-on: ubuntu-latest
    steps:
      - run: echo $contains $startsWith $endsWith $format
        env:
          NAME_1: ${{ contains('Hello world', 'llo') }}
          name_2: ${{ startsWith( github.ref, 'refs/tags' ) }}

          contains: ${{ contains('Hello world', 'llo') }}
          startsWith: ${{ startsWith( github.ref, 'refs/tags' ) }}
          endsWith: ${{ endsWith( github.ref, 'refs/tags' ) }}
          format: ${{ format('Hello {0} {1} {2}', 'Mona', 'the', 'Octocat') }}
          
          # join: ${{ join() }}
          
          # toJSON: ${{ toJSON() }}
          # fromJSON: ${{ fromJSON() }}
          
          # hashFiles: ${{ hashFiles() }}
