
name: my-step-id-actions
on: [ push ]
jobs:
  my-env-job:
    runs-on: ubuntu-latest
    steps:

      - id: my_step_id
        run: echo "::set-output name=MY_NAME::my name is Asim"

      - run: echo ${{ steps.my_step_id.outputs.MY_NAME }}
