name: my-first-actions
# name: Test app

on:
  push:
    branches:
      - master
      - main
    tags:
      - v\d+\.\d+\.\d+


jobs:
  my-first-job:
    
    runs-on: ubuntu-latest
    # runs-on: windows-latest
    # runs-on: macos-latest

    steps:
      # use (community action) to downloads the repo files
      - uses: actions/checkout@v2

      - run: ls -al /home/runner/work/
      - run: echo $MY_ENV
        env:
          MY_ENV: ${{ toJSON(github.event) }}