
name: my-first-actions

on: [ push ]

jobs:
  my-first-job:
    
    runs-on: ubuntu-latest
    # runs-on: windows-latest
    # runs-on: macos-latest

    steps:
      - run: pwd

      - run: ls -al /home/runner/work/

      - uses: actions/checkout@v2
      # use (community action) to downloads the repo files

      - run: ls -al /home/runner/work/
        # drwxr-xr-x  6 runner root   4096 May 28 13:47 .
        # drwxrwxrwx 11 runner docker 4096 May 28 13:47 ..
        # drwxr-xr-x  3 runner docker 4096 May 28 13:47 _PipelineMapping
        # drwxr-xr-x  3 runner docker 4096 May 28 13:47 _actions
        # drwxr-xr-x  4 runner docker 4096 May 28 13:47 _temp
        # drwxr-xr-x  3 runner docker 4096 May 28 13:47 test_actions

      - run: ls -al /home/runner/work/test_actions/
        # drwxr-xr-x 3 runner docker 4096 May 28 13:47 .
        # drwxr-xr-x 6 runner root   4096 May 28 13:47 ..
        # drwxr-xr-x 4 runner docker 4096 May 28 13:47 test_actions

      - run: ls -al /home/runner/work/test_actions/test_actions/
        # drwxr-xr-x 4 runner docker 4096 May 28 13:47 .
        # drwxr-xr-x 3 runner docker 4096 May 28 13:47 ..
        # drwxr-xr-x 8 runner docker 4096 May 28 13:47 .git
        # drwxr-xr-x 3 runner docker 4096 May 28 13:47 .github
        # -rw-r--r-- 1 runner docker   68 May 28 13:47 index.html
        # -rw-r--r-- 1 runner docker  273 May 28 13:47 makefile
      
      - run: |
          uname
          whoami
          echo "Done"
        # Linux
        # runner
        # Done


  my-second-job:
    runs-on: ubuntu-latest
    needs: my-first-job
    
    steps:
      - run: pwd # 
      - run: ls -al /home/runner/work/test_actions/test_actions/
      - uses: actions/checkout@v2
      - run: pwd # /home/runner/work/test_actions/test_actions
      - run: cd /tmp/
      - run: pwd # /home/runner/work/test_actions/test_actions


  my-third-job:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: make all
      

  my-env-job:
    runs-on: ubuntu-latest
    steps:
      - run: echo $MY_NAME
        env:
          MY_NAME: Asim
        # Asim

      - run: echo $NAME_1 $name_2 $Name_3
        env:
          NAME_1: asim
          name_2: bader
          Name_3: Ahmed
        # asim bader Ahmed